// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 7507 $
// $Date: 2015-5-21 $
//
// Licensed under the Apache License, Version 2.0 (the License); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an AS IS BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
//


using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("GreazyGUI")]
[assembly: AssemblyDescription("A tool for identifying lipid mass spectrometry data.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("Greazy")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2015")]
[assembly: AssemblyVersion("0.1.7507")]
[assembly: AssemblyFileVersion("0.1.7507")]
